// <auto-generated />
namespace SalvaDieta.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Troca_Nome_Name_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Troca_Nome_Name_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201607112206237_Troca_Nome_Name_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
