// <auto-generated />
namespace SalvaDieta.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_database_Day_Hour : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_database_Day_Hour));
        
        string IMigrationMetadata.Id
        {
            get { return "201609152118366_Create_database_Day_Hour"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
