// <auto-generated />
namespace SalvaDieta.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alteração_campo_description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alteração_campo_description));
        
        string IMigrationMetadata.Id
        {
            get { return "201607020335484_alteração_campo_description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
